require GIT_SHA

diff --git a/.github/actions/build-aptos-debugger/action.yml b/.github/actions/build-aptos-debugger/action.yml
--- a/.github/actions/build-aptos-debugger/action.yml
+++ b/.github/actions/build-aptos-debugger/action.yml
@@ -13,6 +13,14 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: assert GIT_SHA provided
+      shell: bash
+      run: |
+        if [ -z "${{ inputs.GIT_SHA }}" ]; then
+          echo "GIT_SHA is required"
+          exit 1
+        fi
+
     - uses: actions/checkout@v4
       with:
         ref: ${{ inputs.GIT_SHA }}
diff --git a/.github/actions/get-aptos-debugger/action.yml b/.github/actions/get-aptos-debugger/action.yml
--- a/.github/actions/get-aptos-debugger/action.yml
+++ b/.github/actions/get-aptos-debugger/action.yml
@@ -18,6 +18,14 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: assert GIT_SHA provided
+      shell: bash
+      run: |
+        if [ -z "${{ inputs.GIT_SHA }}" ]; then
+          echo "GIT_SHA is required"
+          exit 1
+        fi
+
     - name: Check Cache
       id: cache-aptos-debugger-binary
       uses: actions/cache@v4
