[cicd] Update for Aptos
* disable tests that require forge
* delete weekly and daily tests until we get there
* eliminate jsonrpc compat warning since that's going to be deleted
anyway
* rename variables eliminating DIEM and NOVI

diff --git a/.github/workflows/ci-post-land.yml b/.github/workflows/ci-post-land.yml
--- a/.github/workflows/ci-post-land.yml
+++ b/.github/workflows/ci-post-land.yml
@@ -82,8 +82,8 @@ jobs:
           $pre_command && cargo x test --no-run --jobs ${max_threads} --unit
         env:
           TARGET_BRANCH: ${{ needs.prepare.outputs.changes-target-branch }}
-          SCCACHE_AWS_ACCESS_KEY_ID: ${{ secrets.ENV_DIEM_S3_AWS_ACCESS_KEY_ID }}
-          SCCACHE_AWS_SECRET_ACCESS_KEY: ${{ secrets.ENV_DIEM_S3_AWS_SECRET_ACCESS_KEY }}
+          SCCACHE_AWS_ACCESS_KEY_ID: ${{ secrets.ENV_S3_AWS_ACCESS_KEY_ID }}
+          SCCACHE_AWS_SECRET_ACCESS_KEY: ${{ secrets.ENV_S3_AWS_SECRET_ACCESS_KEY }}
       - uses: ./.github/actions/build-teardown
 
   # In the future when the script can differentiate between target branches for each auto run then we'll
@@ -119,9 +119,9 @@ jobs:
           recreate: false
           allure_configuration: ./allure-configuration
         env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.ENV_DIEM_S3_AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.ENV_DIEM_S3_AWS_SECRET_ACCESS_KEY }}
-          AWS_DEFAULT_REGION: ${{ secrets.ENV_DIEM_S3_AWS_REGION }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.ENV_S3_AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.ENV_S3_AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: ${{ secrets.ENV_S3_AWS_REGION }}
 
   build_ci_base_docker_image:
     needs: prepare
@@ -150,77 +150,78 @@ jobs:
         run: |
           docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
 
-  run-forge-test-pre-release-suite:
-    needs: prepare
-    name: Run the pre-release suite of Forge Test
-    runs-on: self-hosted
-    if: ${{  startsWith(needs.prepare.outputs.changes-target-branch, 'release') }}
-    # The pre-release suite run time varies 1~1.5 hr.
-    timeout-minutes: 120
-    steps:
-      - uses: actions/checkout@v2.4.0
-        with:
-          fetch-depth: 0 #get all the history!!!
-      - name: set_env
-        id: set_env
-        run: |
-          HEAD_GIT_REV=$(git rev-parse --short=8 HEAD)
-          echo "HEAD_GIT_REV=$HEAD_GIT_REV" >> $GITHUB_ENV
-          IMAGE_TAG=$(echo ${GITHUB_REF#refs/heads/})_$HEAD_GIT_REV
-          echo $IMAGE_TAG
-          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
-      - name: poll_images
-        # Poll until images are ready
-        env:
-          AWS_REGION: us-west-2
-          RETRIES: 30
-        run: |
-          set +e
-          retry=0
-          status=1
-          while [[ $status != 0 && $retry -lt $RETRIES ]]; do
-            status=0
-            for image in diem/validator diem/validator_tcb diem/init diem/forge; do
-              aws ecr describe-images --region $AWS_REGION --repository-name $image --image-ids=imageTag=$IMAGE_TAG
-              status=$((status + $?))
-            done
-            retry=$((retry + 1))
-            if [[ $status != 0 ]] ; then
-              echo "CI has not pushed all images to ECR."
-              echo "Wait $((1*$retry)) of $((1*$RETRIES)) minutes before retry."
-              sleep 1m
-            fi
-          done
-          exit $status
-      - name: Run Forge Test
-        run: |
-          date
-          BASE_GIT_REV=$(git rev-parse $HEAD_GIT_REV^)
-          ./scripts/fgi/run --tag $IMAGE_TAG --timeout-secs 7200 \
-            --env SLACK_CHANGELOG_URL=${{ secrets.WEBHOOK_FORGE }} \
-            --changelog $BASE_GIT_REV $HEAD_GIT_REV \
-            --suite pre_release
-      - name: Push alert
-        if: ${{ failure() }}
-        run: |
-          jq -n \
-            --arg msg "*${{ github.job }}* job in ${{ github.workflow }} workflow failed with $IMAGE_TAG." \
-            --arg url "https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}" \
-            '{
-              "attachments": [
-                {
-                  "text": $msg,
-                  "actions": [
-                    {
-                      "type": "button",
-                      "text": "Visit Job",
-                      "url": $url
-                    }
-                  ]
-                }
-              ]
-            }' > /tmp/payload
-          curl -X POST -H 'Content-type: application/json' -d @/tmp/payload ${{ secrets.WEBHOOK_FORGE }}
+# Disabled post migration to aptos
+#  run-forge-test-pre-release-suite:
+#    needs: prepare
+#    name: Run the pre-release suite of Forge Test
+#    runs-on: self-hosted
+#    if: ${{  startsWith(needs.prepare.outputs.changes-target-branch, 'release') }}
+#    # The pre-release suite run time varies 1~1.5 hr.
+#    timeout-minutes: 120
+#    steps:
+#      - uses: actions/checkout@v2.4.0
+#        with:
+#          fetch-depth: 0 #get all the history!!!
+#      - name: set_env
+#        id: set_env
+#        run: |
+#          HEAD_GIT_REV=$(git rev-parse --short=8 HEAD)
+#          echo "HEAD_GIT_REV=$HEAD_GIT_REV" >> $GITHUB_ENV
+#          IMAGE_TAG=$(echo ${GITHUB_REF#refs/heads/})_$HEAD_GIT_REV
+#          echo $IMAGE_TAG
+#          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
+#      - name: poll_images
+#        # Poll until images are ready
+#        env:
+#          AWS_REGION: us-west-2
+#          RETRIES: 30
+#        run: |
+#          set +e
+#          retry=0
+#          status=1
+#          while [[ $status != 0 && $retry -lt $RETRIES ]]; do
+#            status=0
+#            for image in diem/validator diem/validator_tcb diem/init diem/forge; do
+#              aws ecr describe-images --region $AWS_REGION --repository-name $image --image-ids=imageTag=$IMAGE_TAG
+#              status=$((status + $?))
+#            done
+#            retry=$((retry + 1))
+#            if [[ $status != 0 ]] ; then
+#              echo "CI has not pushed all images to ECR."
+#              echo "Wait $((1*$retry)) of $((1*$RETRIES)) minutes before retry."
+#              sleep 1m
+#            fi
+#          done
+#          exit $status
+#      - name: Run Forge Test
+#        run: |
+#          date
+#          BASE_GIT_REV=$(git rev-parse $HEAD_GIT_REV^)
+#          ./scripts/fgi/run --tag $IMAGE_TAG --timeout-secs 7200 \
+#            --env SLACK_CHANGELOG_URL=${{ secrets.WEBHOOK_FORGE }} \
+#            --changelog $BASE_GIT_REV $HEAD_GIT_REV \
+#            --suite pre_release
+#      - name: Push alert
+#        if: ${{ failure() }}
+#        run: |
+#          jq -n \
+#            --arg msg "*${{ github.job }}* job in ${{ github.workflow }} workflow failed with $IMAGE_TAG." \
+#            --arg url "https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}}" \
+#            '{
+#              "attachments": [
+#                {
+#                  "text": $msg,
+#                  "actions": [
+#                    {
+#                      "type": "button",
+#                      "text": "Visit Job",
+#                      "url": $url
+#                    }
+#                  ]
+#                }
+#              ]
+#            }' > /tmp/payload
+#          curl -X POST -H 'Content-type: application/json' -d @/tmp/payload ${{ secrets.WEBHOOK_FORGE }}
 
   build-release-images:
     needs: prepare
@@ -313,39 +314,40 @@ jobs:
           docker login --username AWS --password-stdin "${AWS_ECR_ACCOUNT_URL}"
           docker/docker_republish.sh -t ${BRANCH}_${GIT_REV} -r ${AWS_ECR_ACCOUNT_URL} -d
 
-  rustdoc:
-    needs: prepare
-    if: ${{ needs.prepare.outputs.changes-target-branch == 'main' && needs.prepare.outputs.rust-changes == 'true'}}
-    runs-on: ubuntu-20.04
-    container:
-      image: ghcr.io/diem/diem_build_environment:${{ needs.prepare.outputs.changes-target-branch }}
-      volumes:
-        - "${{github.workspace}}:/opt/git/diem"
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2.4.0
-      - uses: ./.github/actions/build-setup
-      - uses: actions/cache@v2.1.6
-        with:
-          path: "/opt/cargo/git\n/opt/cargo/registry\n/opt/cargo/.package-cache"
-          key: crates-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
-          restore-keys: "crates-${{ runner.os }}"
-      - name: Build Documentation
-        # Build the rust crate docs
-        # Use `RUSTC_BOOTSTRAP` in order to use the `--enable-index-page` flag of rustdoc
-        # This is needed in order to generate a landing page `index.html` for workspaces
-        run: cargo doc --no-deps --workspace --lib
-        env:
-          RUSTC_BOOTSTRAP: 1
-          RUSTDOCFLAGS: "-Z unstable-options --enable-index-page"
-          CARGO_INCREMENTAL: 0
-          RUSTFLAGS: -D warnings
-      - name: copy API specification doc into target/doc/diem_api
-        run : cp api/doc/openapi.yaml target/doc/diem_api/openapi.yaml && cp api/doc/spec.html target/doc/diem_api/spec.html
-      - name: Deploy Docs
-        uses: peaceiris/actions-gh-pages@v3.8.0
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_branch: gh-pages
-          publish_dir: ./target/doc
-          force_orphan: true
+# Disabled pending migration to aptos
+#  rustdoc:
+#    needs: prepare
+#    if: ${{ needs.prepare.outputs.changes-target-branch == 'main' && needs.prepare.outputs.rust-changes == 'true'}}
+#    runs-on: ubuntu-20.04
+#    container:
+#      image: ghcr.io/diem/diem_build_environment:${{ needs.prepare.outputs.changes-target-branch }}
+#      volumes:
+#        - "${{github.workspace}}:/opt/git/diem"
+#    steps:
+#      - name: Checkout repository
+#        uses: actions/checkout@v2.4.0
+#      - uses: ./.github/actions/build-setup
+#      - uses: actions/cache@v2.1.6
+#        with:
+#          path: "/opt/cargo/git\n/opt/cargo/registry\n/opt/cargo/.package-cache"
+#          key: crates-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
+#          restore-keys: "crates-${{ runner.os }}"
+#      - name: Build Documentation
+#        # Build the rust crate docs
+#        # Use `RUSTC_BOOTSTRAP` in order to use the `--enable-index-page` flag of rustdoc
+#        # This is needed in order to generate a landing page `index.html` for workspaces
+#        run: cargo doc --no-deps --workspace --lib
+#        env:
+#          RUSTC_BOOTSTRAP: 1
+#          RUSTDOCFLAGS: "-Z unstable-options --enable-index-page"
+#          CARGO_INCREMENTAL: 0
+#          RUSTFLAGS: -D warnings
+#      - name: copy API specification doc into target/doc/diem_api
+#        run : cp api/doc/openapi.yaml target/doc/diem_api/openapi.yaml && cp api/doc/spec.html target/doc/diem_api/spec.html
+#      - name: Deploy Docs
+#        uses: peaceiris/actions-gh-pages@v3.8.0
+#        with:
+#          github_token: ${{ secrets.GITHUB_TOKEN }}
+#          publish_branch: gh-pages
+#          publish_dir: ./target/doc
+#          force_orphan: true
diff --git a/.github/workflows/ci-test.yml b/.github/workflows/ci-test.yml
--- a/.github/workflows/ci-test.yml
+++ b/.github/workflows/ci-test.yml
@@ -46,13 +46,13 @@ jobs:
         run: ./scripts/git-checks.sh
       - id: changes
         name: determine changes
-        uses: diem/actions/changes@faadd16607b77dfa2231a8f366883e01717b3225
+        uses: aptos-labs/actions/changes@0.1
         with:
           workflow-file: ci-test.yml
           github-token: ${{secrets.GITHUB_TOKEN}}
       - id: need-build-images
         name: find changes need image build.
-        uses: diem/actions/matches@faadd16607b77dfa2231a8f366883e01717b3225
+        uses: aptos-labs/actions/matches@0.1
         with:
           pattern: '^documentation\|^developers.diem.com'
           invert: "true"
@@ -105,44 +105,44 @@ jobs:
           echo "::set-output name=changes-found::$(echo $res)";
       - id: rust-changes
         name: find rust/cargo changes.
-        uses: diem/actions/matches@faadd16607b77dfa2231a8f366883e01717b3225
+        uses: aptos-labs/actions/matches@0.1
         with:
           pattern: '^documentation\|^docker\|^scripts\|^developers.diem.com'
           invert: "true"
       - id: non-rust-lint-changes
         name: find shell/dockerfile changes
-        uses: diem/actions/matches@faadd16607b77dfa2231a8f366883e01717b3225
+        uses: aptos-labs/actions/matches@0.1
         with:
           pattern: 'Dockerfile$\|.*.sh$\|^developers.diem.com\|^shuffle'
       - id: helm-changes
         name: find helm changes
-        uses: diem/actions/matches@faadd16607b77dfa2231a8f366883e01717b3225
+        uses: aptos-labs/actions/matches@0.1
         with:
           pattern: "^helm"
       - id: dev-setup-sh-changes
         name: find dev-setup.sh/base docker image changes
-        uses: diem/actions/matches@faadd16607b77dfa2231a8f366883e01717b3225
+        uses: aptos-labs/actions/matches@0.1
         with:
           pattern: 'docker/ci\|scripts/dev_setup.sh'
       - id: docker-compose-changes
         name: find changes that should trigger docker compose testing.
-        uses: diem/actions/matches@faadd16607b77dfa2231a8f366883e01717b3225
+        uses: aptos-labs/actions/matches@0.1
         with:
           pattern: "^documentation"
           invert: "true"
       - id: website-changes
         name: find website changes.
-        uses: diem/actions/matches@faadd16607b77dfa2231a8f366883e01717b3225
+        uses: aptos-labs/actions/matches@0.1
         with:
           pattern: '^documentation\|^developers.diem.com\|^.github'
       - id: test-coverage
         name: check if we should see if code coverage still works.
-        uses: diem/actions/matches@faadd16607b77dfa2231a8f366883e01717b3225
+        uses: aptos-labs/actions/matches@0.1
         with:
           pattern: '^rust.toolchain\|^x.toml\|^devtools\|^.github\|common/logger'
       - id: test-api-spec
         name: find api changes.
-        uses: diem/actions/matches@faadd16607b77dfa2231a8f366883e01717b3225
+        uses: aptos-labs/actions/matches@0.1
         with:
           pattern: '^api\|^scripts/dev_setup.sh'
 
@@ -185,18 +185,18 @@ jobs:
           fetch-depth: 0 #get all the history!!!
       - id: changes
         name: determine changes
-        uses: diem/actions/changes@faadd16607b77dfa2231a8f366883e01717b3225
+        uses: aptos-labs/actions/changes@0.1
         with:
           workflow-file: docker-publish.yml
       - name: setup_aws_ecr_login
         run: |
-          echo 'AWS_ECR_ACCOUNT_URL=${{ secrets.ENV_NOVI_ECR_AWS_ACCOUNT_NUM }}.dkr.ecr.${{ secrets.ENV_NOVI_ECR_AWS_REGION }}.amazonaws.com' >> $GITHUB_ENV
+          echo 'AWS_ECR_ACCOUNT_URL=${{ secrets.ENV_ECR_AWS_ACCOUNT_NUM }}.dkr.ecr.${{ secrets.ENV_ECR_AWS_REGION }}.amazonaws.com' >> $GITHUB_ENV
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
-          aws-access-key-id: ${{ secrets.ENV_NOVI_ECR_AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.ENV_NOVI_ECR_AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.ENV_NOVI_ECR_AWS_REGION }}
+          aws-access-key-id: ${{ secrets.ENV_ECR_AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.ENV_ECR_AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.ENV_ECR_AWS_REGION }}
       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1.3.3
@@ -232,7 +232,7 @@ jobs:
           BRANCH="$CHANGES_TARGET_BRANCH"
           GIT_REV=$(git rev-parse --short=8 HEAD)
           echo "::set-output name=head-tag::land_$GIT_REV";
-          aws ecr get-login-password --region ${{ secrets.ENV_NOVI_ECR_AWS_REGION }} | \
+          aws ecr get-login-password --region ${{ secrets.ENV_ECR_AWS_REGION }} | \
           docker login --username AWS --password-stdin "${AWS_ECR_ACCOUNT_URL}"
           docker/docker_republish.sh -t pre_${BRANCH}_${GIT_REV} -o land_${GIT_REV} -r ${AWS_ECR_ACCOUNT_URL} -d -i "${{ matrix.target_images }}"
       - name: Early terminate workflow
@@ -850,125 +850,126 @@ jobs:
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
 
-  land-blocking-test-forge:
-    name: Run land blocking test in Forge
-    runs-on: self-hosted
-    needs: [prepare, build-images, need-base-images]
-    if: ${{ always() && needs.build-images.result=='success' && needs.prepare.outputs.test-land-blocking == 'true' }}
-    outputs:
-      forge-result: ${{ steps.post-test-result.outputs.forge-result }}
-    timeout-minutes: 45
-    steps:
-      - uses: actions/checkout@v2.4.0
-        with:
-          # This ensures that the tip of the PR is checked out instead of the merge between the base ref and the tip
-          # On `push` this value will be empty and will "do-the-right-thing"
-          ref: ${{ github.event.pull_request.head.sha }}
-      - name: Launch forge test
-        run: |
-          set +e
-          date
-          export FGI_OUTPUT_LOG=$(mktemp)
-          echo "FGI_OUTPUT_LOG=$FGI_OUTPUT_LOG" >> $GITHUB_ENV
-          cmd=""
-          if ${{ needs.need-base-images.result!='success' }}; then
-            cmd="./scripts/fgi/run --tag ${{ needs.build-images.outputs.head-tag }} --suite land_blocking --report forge_report.json"
-          else
-            cmd="./scripts/fgi/run --tag ${{ needs.build-images.outputs.head-tag }} --base-image-tag ${{ needs.need-base-images.outputs.prev-tag }} --suite land_blocking_compat --report forge_report.json"
-          fi
-          eval $cmd
-          ret=$?
-          echo "fgi exit code: $ret"
-          echo "FGI_REPRO_CMD=$cmd" >> $GITHUB_ENV
-          echo "FGI_EXIT_CODE=$ret" >> $GITHUB_ENV
-      - name: Post test results on PR
-        uses: actions/github-script@v4.0.2
-        with:
-          github-token: ${{secrets.GITHUB_TOKEN}}
-          script: |
-            // Find the number of the pull request that trigggers this push
-            let pr_num = ${{ needs.prepare.outputs.changes-pull-request-number }};
-            if (!pr_num) {
-              console.warn("Did not find pull request num in previous step");
-              console.log("GH event payload\n", context.payload);
-              return;
-            }
-            // Read and check forge test results
-            let should_fail = false;
-            let env_vars = process.env;
-            let body = '';
-            const fsp = require('fs').promises;
-            try {
-              data = await fsp.readFile('forge_report.json', 'utf-8');
-              var result = JSON.parse(data);
-              // TODO - set P/F based on metrics TPS, latency
-              body = `Forge Test Result
-            \`\`\`
-            ${result.text}
-            ${result.logs}
-            ${result.dashboard}
-            \`\`\`
-            `;
-              // Check FGI exit code for errors
-              if (parseInt(env_vars.FGI_EXIT_CODE) != 0) {
-                body += "\n :exclamation: Forge Test failed - non-zero exit code for `fgi` \n"
-                should_fail = true;
-              }
-            } catch (err) {
-              if (err.code === 'ENOENT') {
-                body = "Forge Test failed - no test report found.\n";
-              } else {
-                body = "Forge Test runner failed.";
-                console.error(err);
-              }
-              body += " See https://github.com/diem/diem/actions/runs/${{github.run_id}}";
-              // Post comment on PR then fail this workflow
-              should_fail = true;
-            }
-            // Add repro cmd to message
-            try {
-              body += "\nRepro cmd:\n";
-              body += `
-              \`\`\`
-              ${env_vars.FGI_REPRO_CMD}
-              \`\`\`
-              `
-            } catch (err) {
-              if (err.code === 'ReferenceError') {
-                console.error("One of the following env vars is not set");
-              } else {
-                body += "[GHA DEBUG]\nFound error in actions/github-script\n";
-                body += err;
-              }
-            }
-            // Post test result on original pull request
-            try {
-              if (!should_fail) {
-                body += "\n :tada: Land-blocking forge test passed! :ok_hand:"
-              }
-              await github.issues.createComment(
-                  {
-                    issue_number: pr_num,
-                    owner: context.repo.owner,
-                    repo: context.repo.repo,
-                    body: body,
-                  }
-              );
-            } catch (err) {
-              if (err.status === 401) {
-                // Fail silently for auth but log to console.
-                console.warn("GH token has expired when trying to POST\n", err);
-              } else {
-                console.error("HttpError other than 401 is not bypassed");
-                throw err;
-              }
-            }
-            // Fail the workflow if test fails
-            if (should_fail) {
-              throw "Land-blocking test failed";
-            }
-      - name: Early terminate workflow
-        if: ${{ failure() }}
-        uses: ./.github/actions/early-terminator
-        with:
-          github-token: ${{secrets.GITHUB_TOKEN}}
+# Disabled pending migration to aptos
+#  land-blocking-test-forge:
+#    name: Run land blocking test in Forge
+#    runs-on: self-hosted
+#    needs: [prepare, build-images, need-base-images]
+#    if: ${{ always() && needs.build-images.result=='success' && needs.prepare.outputs.test-land-blocking == 'true' }}
+#    outputs:
+#      forge-result: ${{ steps.post-test-result.outputs.forge-result }}
+#    timeout-minutes: 45
+#    steps:
+#      - uses: actions/checkout@v2.4.0
+#        with:
+#          # This ensures that the tip of the PR is checked out instead of the merge between the base ref and the tip
+#          # On `push` this value will be empty and will "do-the-right-thing"
+#          ref: ${{ github.event.pull_request.head.sha }}
+#      - name: Launch forge test
+#        run: |
+#          set +e
+#          date
+#          export FGI_OUTPUT_LOG=$(mktemp)
+#          echo "FGI_OUTPUT_LOG=$FGI_OUTPUT_LOG" >> $GITHUB_ENV
+#          cmd=""
+#          if ${{ needs.need-base-images.result!='success' }}; then
+#            cmd="./scripts/fgi/run --tag ${{ needs.build-images.outputs.head-tag }} --suite land_blocking --report forge_report.json"
+#          else
+#            cmd="./scripts/fgi/run --tag ${{ needs.build-images.outputs.head-tag }} --base-image-tag ${{ needs.need-base-images.outputs.prev-tag }} --suite land_blocking_compat --report forge_report.json"
+#          fi
+#          eval $cmd
+#          ret=$?
+#          echo "fgi exit code: $ret"
+#          echo "FGI_REPRO_CMD=$cmd" >> $GITHUB_ENV
+#          echo "FGI_EXIT_CODE=$ret" >> $GITHUB_ENV
+#      - name: Post test results on PR
+#        uses: actions/github-script@v4.0.2
+#        with:
+#          github-token: ${{secrets.GITHUB_TOKEN}}
+#          script: |
+#            // Find the number of the pull request that trigggers this push
+#            let pr_num = ${{ needs.prepare.outputs.changes-pull-request-number }};
+#            if (!pr_num) {
+#              console.warn("Did not find pull request num in previous step");
+#              console.log("GH event payload\n", context.payload);
+#              return;
+#            }
+#            // Read and check forge test results
+#            let should_fail = false;
+#            let env_vars = process.env;
+#            let body = '';
+#            const fsp = require('fs').promises;
+#            try {
+#              data = await fsp.readFile('forge_report.json', 'utf-8');
+#              var result = JSON.parse(data);
+#              // TODO - set P/F based on metrics TPS, latency
+#              body = `Forge Test Result
+#            \`\`\`
+#            ${result.text}
+#            ${result.logs}
+#            ${result.dashboard}
+#            \`\`\`
+#            `;
+#              // Check FGI exit code for errors
+#              if (parseInt(env_vars.FGI_EXIT_CODE) != 0) {
+#                body += "\n :exclamation: Forge Test failed - non-zero exit code for `fgi` \n"
+#                should_fail = true;
+#              }
+#            } catch (err) {
+#              if (err.code === 'ENOENT') {
+#                body = "Forge Test failed - no test report found.\n";
+#              } else {
+#                body = "Forge Test runner failed.";
+#                console.error(err);
+#              }
+#              body += " See https://github.com/aptos-labs/diem-internal/actions/runs/${{github.run_id}}";
+#              // Post comment on PR then fail this workflow
+#              should_fail = true;
+#            }
+#            // Add repro cmd to message
+#            try {
+#              body += "\nRepro cmd:\n";
+#              body += `
+#              \`\`\`
+#              ${env_vars.FGI_REPRO_CMD}
+#              \`\`\`
+#              `
+#            } catch (err) {
+#              if (err.code === 'ReferenceError') {
+#                console.error("One of the following env vars is not set");
+#              } else {
+#                body += "[GHA DEBUG]\nFound error in actions/github-script\n";
+#                body += err;
+#              }
+#            }
+#            // Post test result on original pull request
+#            try {
+#              if (!should_fail) {
+#                body += "\n :tada: Land-blocking forge test passed! :ok_hand:"
+#              }
+#              await github.issues.createComment(
+#                  {
+#                    issue_number: pr_num,
+#                    owner: context.repo.owner,
+#                    repo: context.repo.repo,
+#                    body: body,
+#                  }
+#              );
+#            } catch (err) {
+#              if (err.status === 401) {
+#                // Fail silently for auth but log to console.
+#                console.warn("GH token has expired when trying to POST\n", err);
+#              } else {
+#                console.error("HttpError other than 401 is not bypassed");
+#                throw err;
+#              }
+#            }
+#            // Fail the workflow if test fails
+#            if (should_fail) {
+#              throw "Land-blocking test failed";
+#            }
+#      - name: Early terminate workflow
+#        if: ${{ failure() }}
+#        uses: ./.github/actions/early-terminator
+#        with:
+#          github-token: ${{secrets.GITHUB_TOKEN}}
