ci: disable code-coverage job as its currently broken
Closes: #9516

diff --git a/.github/workflows/ci-test.yml b/.github/workflows/ci-test.yml
--- a/.github/workflows/ci-test.yml
+++ b/.github/workflows/ci-test.yml
@@ -825,38 +825,39 @@ jobs:
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
 
-  coverage-unit-test:
-    runs-on: ubuntu-20.04-xl
-    timeout-minutes: 30
-    needs: prepare
-    if: ${{ needs.prepare.outputs.test-test-coverage == 'true' }}
-    container:
-      image: ghcr.io/diem/diem_build_environment:${{ needs.prepare.outputs.changes-target-branch }}
-      volumes:
-        - "${{github.workspace}}:/opt/git/diem"
-    steps:
-      - uses: actions/checkout@v2.3.4
-        with:
-          ref: ${{ github.event.pull_request.head.sha }}
-      - uses: ./.github/actions/build-setup
-      - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
-        with:
-          key: ${{ needs.prepare.outputs.changes-target-branch }}
-      - name: run coverage tests and verify coverage is calculated.
-        run: |
-          cargo xtest --html-cov-dir=/tmp/results/ -p diem-logger
-          export line_coverage=$( cat /tmp/results/index.html | grep '<abbr' | head -1 | sed 's/<[^>]*>//g' |  sed 's/\..*//g' | sed 's/[[:blank:]]//g' )
-          echo Line Coverage: $line_coverage
-          if (( line_coverage < 80 )); then
-            echo Coverage appears to be broken, diem/logger should report more than 80% line coverage.
-            exit 1;
-          fi
-      - uses: ./.github/actions/build-teardown
-      - name: Early terminate workflow
-        if: ${{ failure() }}
-        uses: ./.github/actions/early-terminator
-        with:
-          github-token: ${{secrets.GITHUB_TOKEN}}
+  # Disabling temporarily since code coverage is currently broken with the latest rust release
+  # coverage-unit-test:
+  #   runs-on: ubuntu-20.04-xl
+  #   timeout-minutes: 30
+  #   needs: prepare
+  #   if: ${{ needs.prepare.outputs.test-test-coverage == 'true' }}
+  #   container:
+  #     image: ghcr.io/diem/diem_build_environment:${{ needs.prepare.outputs.changes-target-branch }}
+  #     volumes:
+  #       - "${{github.workspace}}:/opt/git/diem"
+  #   steps:
+  #     - uses: actions/checkout@v2.3.4
+  #       with:
+  #         ref: ${{ github.event.pull_request.head.sha }}
+  #     - uses: ./.github/actions/build-setup
+  #     - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
+  #       with:
+  #         key: ${{ needs.prepare.outputs.changes-target-branch }}
+  #     - name: run coverage tests and verify coverage is calculated.
+  #       run: |
+  #         cargo xtest --html-cov-dir=/tmp/results/ -p diem-logger
+  #         export line_coverage=$( cat /tmp/results/index.html | grep '<abbr' | head -1 | sed 's/<[^>]*>//g' |  sed 's/\..*//g' | sed 's/[[:blank:]]//g' )
+  #         echo Line Coverage: $line_coverage
+  #         if (( line_coverage < 80 )); then
+  #           echo Coverage appears to be broken, diem/logger should report more than 80% line coverage.
+  #           exit 1;
+  #         fi
+  #     - uses: ./.github/actions/build-teardown
+  #     - name: Early terminate workflow
+  #       if: ${{ failure() }}
+  #       uses: ./.github/actions/early-terminator
+  #       with:
+  #         github-token: ${{secrets.GITHUB_TOKEN}}
 
   helm-test:
     runs-on: ubuntu-20.04-xl
